"""Static templates used by `x402-gateway server scaffold`."""

from __future__ import annotations

from pathlib import Path

PROVIDER_TEMPLATE = """\
# Generated by `x402-gateway server scaffold`. Fill the TODO lines before
# running `x402-gateway server start provider.yml`.

name: {name}
title: "{name}"
description: "TODO: describe what this API does in one sentence"
category: other                # one of: ai_ml, cloud, compute, data, devtools,
                               # finance, identity, media, messaging, other,
                               # productivity, search, security, shopping,
                               # storage, translation
version: v1

forward_url: {forward_url}

routing:
  type: proxy
  # auth:
  #   method: header
  #   key: Authorization
  #   prefix: "Bearer "
  #   value_from_env: UPSTREAM_TOKEN

operator:
  network: {network}             # tron-mainnet / tron-shasta / tron-nile
                                 # / bsc-mainnet / bsc-testnet
  currencies:
    usd: ["USDT"]
  recipient: "TODO_YOUR_WALLET"  # paste your TRON / EVM address here
  scheme: exact_permit
  # facilitator_url: https://facilitator.bankofai.io  # uncomment in prod

# Optional: declare named recipients so endpoints can split payments
# recipients:
#   vendor:
#     account: "TVendorWallet"
#     label: "Vendor"

endpoints:
  - method: GET
    path: /v1/example
    description: "TODO: describe this endpoint"
    metering:
      dimensions:
        - direction: usage
          unit: requests
          scale: 1
          tiers:
            - price_usd: 0.001

  - method: GET
    path: /health
"""


def write_provider_template(
    *,
    output_dir: Path,
    name: str,
    forward_url: str,
    network: str,
    overwrite: bool = False,
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    target = output_dir / "provider.yml"
    if target.exists() and not overwrite:
        raise FileExistsError(f"{target} already exists; pass --overwrite to replace")

    target.write_text(
        PROVIDER_TEMPLATE.format(name=name, forward_url=forward_url, network=network)
    )
    return target
